apiVersion: v1
kind: Service
metadate:
  name: architeuthis-service
spec:
  type: NodePort
  selector:
    app: architeuthis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000