apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: architeuthis-ingress
spec:
  rules:
    - host: architeuthis.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: architeuthis-service
                port:
                  number: 80