apiVersion : apps/v1
kind: Deployment
metadata:
  name: architeuthis-deploy
  labels:
    app: architeuthis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architeuthis
  template:
    metadata:
      labels:
        app: architeuthis
    spec:
      containers:
      - name: architeuthis-container
        image: eylir/architeuthis:latest
        imagePullPolicy: Always