apiVersion : apps/v1
kind: Deployment
metadata:
  name: architeuthis-deploy
  labels:
    app: architeuthis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architeuthis
  template:
    metadata:
      labels:
        app: architeuthis
    spec:
      containers:
      - name: architeuthis-container
        image: eylir/python-app:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password-secret
              key: redis-password